# Build arguments a pipeline can override.
ARG BUILD_CONFIGURATION=production
ARG APP_VERSION=1.0.0

FROM {{container_node_image}} AS build
ARG BUILD_CONFIGURATION
WORKDIR /app
COPY {{container_manifest_files}} ./
RUN {{container_install}}
COPY . .
RUN {{container_ng}} build --configuration $BUILD_CONFIGURATION

FROM docker.io/nginxinc/nginx-unprivileged:alpine AS final
ARG APP_VERSION
LABEL org.opencontainers.image.version=$APP_VERSION
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/{{container_project}}/browser /usr/share/nginx/html
EXPOSE 8080
